Revert "Add CodeQL"
This reverts commit 71c414a2b0b4e3c8ba5860af76e7f46f6a60ac20.
>  Error: We were unable to automatically build your code. Please replace the call to the autobuild action with your custom build steps.  Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20211025/x64/codeql/cpp/tools/autobuild.sh with arguments .

```
  /opt/hostedtoolcache/CodeQL/0.0.0-20211025/x64/codeql/codeql version --format=terse
  2.7.0
  /opt/hostedtoolcache/CodeQL/0.0.0-20211025/x64/codeql/cpp/tools/autobuild.sh
  + TOOLS_DIR=/opt/hostedtoolcache/CodeQL/0.0.0-20211025/x64/codeql/cpp/tools
  + /opt/hostedtoolcache/CodeQL/0.0.0-20211025/x64/codeql/cpp/tools/detect_source_root

  detect_source_root: Build will be attempted from '.'
  even though no build system was found there.

  + '[' -L _lgtm_detected_source_root ']'
  ++ readlink _lgtm_detected_source_root
  + cd .
  + export CXXFLAGS=-fpermissive
  + CXXFLAGS=-fpermissive
  + configure_prefix_opt=
  + '[' -f configure.ac ']'
  + '[' -f configure.in ']'
  + '[' -f CMakeLists.txt ']'
  + '[' -f meson.build ']'
  + try_configure
  + build_dir=.
  + root_dir=.
  + grep -q 'AC_MSG_.* configure in a separate.* directory' configure.in configure.ac
  + for configure in configure configure.gnu
  + '[' -x configure ']'
  + for configure in configure configure.gnu
  + '[' -x configure.gnu ']'
  + rm -rf _lgtm_build_dir
  + for bootstrap in bootstrap.sh bootstrap autogen.sh
  + '[' -x bootstrap.sh ']'
  + '[' -f bootstrap.sh ']'
  + for bootstrap in bootstrap.sh bootstrap autogen.sh
  + '[' -x bootstrap ']'
  + '[' -f bootstrap ']'
  + for bootstrap in bootstrap.sh bootstrap autogen.sh
  + '[' -x autogen.sh ']'
  + '[' -f autogen.sh ']'
  + '[' -f wscript ']'
  + '[' -f Kbuild ']'
  + '[' -f configure.ac ']'
  + '[' -f configure.in ']'
  ++ echo './*.pro'
  + '[' './*.pro' '!=' './*.pro' ']'
  + exit 0
  + '[' -L _lgtm_detected_source_root ']'
  ++ readlink _lgtm_detected_source_root
  + cd .
  + '[' -d _lgtm_build_dir ']'
  + '[' -f SConstruct ']'
  + '[' -f wscript ']'
  + '[' -f Makefile ']'
  + '[' -f makefile ']'
  + '[' -f GNUmakefile ']'
  + '[' -f build.ninja ']'
  + '[' -d ../_lgtm_build_dir ']'
  + for f in build build.sh
  + '[' -x build ']'
  + for f in build build.sh
  + '[' -x build.sh ']'
  + '[' -f setup.py ']'
  + echo 'Semmle autobuild: no supported build system detected.'
  + exit 1
  Semmle autobuild: no supported build system detected.
  Error: We were unable to automatically build your code. Please replace the call to the autobuild action with your custom build steps.  Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20211025/x64/codeql/cpp/tools/autobuild.sh with arguments .

        Exit code 1 and error was:

```